'use client';
import {useState} from 'react';
import {Card,CardHeader,CardTitle,CardContent} from '@/components/ui/card';
import {Button} from '@/components/ui/button';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import type {DemoStaff} from '@/lib/demo/data';
const money=(n:number)=>`¥${n.toLocaleString('ja-JP')}`;
export default function DemoPayroll({staff,month}:{staff:DemoStaff[];month:string}) {
 const [selected,setSelected]=useState<string|null>(null),[confirmed,setConfirmed]=useState<string[]>([]),[notice,setNotice]=useState('');
 const rows=staff.map((s,i)=>{const base=260000-i%3*20000,commission=35000-i%3*7000,allowance=15000,gross=base+commission+allowance,deductions=48000-i%3*4000;return {...s,base,commission,allowance,gross,deductions,net:gross-deductions};});
 const current=rows.find(r=>r.id===selected);
 return <section className="space-y-6"><div><h2 className="text-2xl font-bold">給与・報酬計算</h2><p className="mt-2 text-sm text-slate-500">{month}の給与一覧・給与明細・確定の操作を体験できます。</p></div><p className="text-xs text-slate-500">支給・控除額は固定の架空サンプルです。税額・社会保険料の実計算、振込、本番への保存は行いません。</p>{notice&&<p role="status" className="p-4 rounded-xl bg-emerald-50">{notice}</p>}<div className="grid sm:grid-cols-3 gap-4">{[['支給総額',money(rows.reduce((s,r)=>s+r.gross,0))],['控除総額',money(rows.reduce((s,r)=>s+r.deductions,0))],['差引支給額',money(rows.reduce((s,r)=>s+r.net,0))]].map(([k,v])=><Card key={k}><CardContent className="p-5"><p className="text-sm text-slate-500">{k}</p><p className="text-2xl font-black mt-3">{v}</p></CardContent></Card>)}</div><div className="overflow-x-auto rounded-xl border bg-white"><table className="w-full whitespace-nowrap text-sm"><thead className="bg-slate-50"><tr>{['スタッフ','基本給','歩合・報奨','手当','総支給','控除','差引支給','状態','明細'].map(h=><th className="p-4 text-left" key={h}>{h}</th>)}</tr></thead><tbody>{rows.map(r=><tr key={r.id} className="border-t"><td className="p-4 font-bold">{r.name}</td>{[r.base,r.commission,r.allowance,r.gross,r.deductions,r.net].map((v,i)=><td className="p-4" key={i}>{money(v)}</td>)}<td className="p-4">{confirmed.includes(`${month}:${r.id}`)?'確定済み':'確認待ち'}</td><td className="p-4"><Button variant="outline" onClick={()=>setSelected(r.id)}>明細を見る</Button></td></tr>)}</tbody></table></div><Button onClick={()=>setNotice('給与CSV出力を体験しました（デモ）。実際の給与ファイルは生成・送信しません。')}>給与CSV出力を体験</Button><Dialog open={!!current} onOpenChange={v=>{if(!v)setSelected(null);}}><DialogContent><DialogHeader><DialogTitle>{current?.name}・{month} 給与明細</DialogTitle><DialogDescription>すべてサンプル値です。実際の給与に影響しません。</DialogDescription></DialogHeader>{current&&<><Card><CardHeader><CardTitle>支給・控除</CardTitle></CardHeader><CardContent className="space-y-3">{[['基本給',current.base],['歩合・報奨',current.commission],['各種手当',current.allowance],['支給合計',current.gross],['控除合計（サンプル）',current.deductions],['差引支給額',current.net]].map(([k,v])=><div key={k} className="flex justify-between border-b pb-2"><span>{k}</span><strong>{money(Number(v))}</strong></div>)}</CardContent></Card><Button onClick={()=>{setConfirmed(old=>[...new Set([...old,`${month}:${current.id}`])]);setSelected(null);setNotice(`${current.name}さんの給与を確定しました（デモ）。振込は行われません。`);}}>確認して確定（デモ）</Button></>}</DialogContent></Dialog></section>;
}
