'use client';
import {useState,type ReactElement} from 'react';
import {Sparkles} from 'lucide-react';
import {Card,CardHeader,CardTitle,CardContent} from '@/components/ui/card';
import {Button} from '@/components/ui/button';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {ResponsiveContainer,AreaChart,Area,BarChart,Bar,LineChart,Line,XAxis,YAxis,CartesianGrid,Tooltip,Legend} from 'recharts';
import {demoSummary,type createDemoData} from '@/lib/demo/data';
const yen=(n:number)=>`¥${Math.round(n).toLocaleString('ja-JP')}`;
const sections=[['overview','概要 (月次トレンド)'],['staff','スタッフ分析'],['store','店舗比較'],['referral','紹介分析'],['channel','流入分析'],['menu','メニュー分析'],['coupon','価格・文言最適化'],['regression','回帰分析 (要因分析)'],['forecast','将来予測 (SARIMAX)'],['repeat','リピート分析'],['ltv','LTV・リピーター予測']];
export default function DemoAnalytics({dataset,month,onAsk}:{dataset:ReturnType<typeof createDemoData>;month:string;onAsk:(s:string)=>void}) {
 const [section,setSection]=useState('overview'),[staffId,setStaffId]=useState('all'),[menu,setMenu]=useState('all');
 const all=dataset.reservations.filter(r=>r.status!=='キャンセル'),rows=all.filter(r=>r.date.startsWith(month)),summary=demoSummary(all,dataset.expenses,month);
 const months=[...new Set(all.map(r=>r.date.slice(0,7)))].sort();
 const trend=months.map(m=>({name:m,...demoSummary(all,dataset.expenses,m)}));
 const staff=dataset.staff.map(s=>{const visits=rows.filter(r=>r.staffId===s.id),revenue=visits.reduce((v,r)=>v+r.amount,0);return {...s,count:visits.length,revenue,average:visits.length?revenue/visits.length:0,repeat:visits.length?100*visits.filter(r=>!r.isNew).length/visits.length:0};});
 const menuNames=[...new Set(all.map(r=>r.menu))];
 const menus=menuNames.map(name=>{const visits=rows.filter(r=>r.menu===name);return {name,count:visits.length,revenue:visits.reduce((v,r)=>v+r.amount,0)};});
 const channels=['HOT PEPPER Beauty','LINE','紹介','Instagram','その他'].map((name,i)=>{const visits=rows.filter(r=>Number(r.id.replace(/\D/g,''))%5===i);return {name,count:visits.length,revenue:visits.reduce((v,r)=>v+r.amount,0)};});
 const forecast=[{name:'10月',base:2480000,low:2260000,high:2710000},{name:'11月',base:2540000,low:2300000,high:2820000},{name:'12月',base:2790000,low:2490000,high:3100000}];
 const sample=<p className="text-xs text-slate-500">以下は営業説明用の固定サンプルです。選択月の実集計やAI・統計モデルの実行結果ではありません。</p>;
 return <section className="space-y-6"><div><h2 className="text-2xl font-bold flex gap-2 items-center"><Sparkles className="text-purple-500"/>高度分析</h2><p className="text-slate-500 text-sm mt-2">売上や来店人数の傾向、影響要因を分析します。</p></div>
  <Tabs value={section} onValueChange={setSection}><TabsList className="h-auto flex flex-wrap justify-start bg-slate-100 p-1 rounded-xl">{sections.map(([id,name])=><TabsTrigger key={id} value={id} className="px-3 py-2 rounded-lg data-[state=active]:text-purple-600">{name}</TabsTrigger>)}</TabsList>
  <TabsContent value="overview" className="space-y-5 mt-6"><Metrics entries={[['売上',yen(summary.revenue)],['来店数',`${summary.visits}件`],['客単価',yen(summary.average)],['営業利益（概算）',yen(summary.profit)]]}/><div className="grid xl:grid-cols-2 gap-5"><Plot title="月次売上・経費推移"><AreaChart data={trend}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name" tick={{fontSize:10}}/><YAxis tickFormatter={v=>`${v/10000}万`}/><Tooltip formatter={v=>yen(Number(v))}/><Legend/><Area dataKey="revenue" name="売上" stroke="#8b5cf6" fill="#ede9fe"/><Area dataKey="cost" name="経費" stroke="#f59e0b" fill="#fef3c7"/></AreaChart></Plot><Plot title="新規・再来の月次推移"><BarChart data={trend}><XAxis dataKey="name" tick={{fontSize:10}}/><YAxis/><Tooltip/><Legend/><Bar dataKey="newVisits" name="新規" stackId="a" fill="#a78bfa"/><Bar dataKey="repeatVisits" name="再来" stackId="a" fill="#34d399"/></BarChart></Plot></div></TabsContent>
  <TabsContent value="staff" className="space-y-5 mt-6"><label className="text-sm font-bold">スタッフ<select className="block border rounded-lg p-2 bg-white mt-2" value={staffId} onChange={e=>setStaffId(e.target.value)}><option value="all">全スタッフ</option>{staff.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><Plot title="スタッフ別売上"><BarChart data={staff.filter(s=>staffId==='all'||s.id===staffId)}><XAxis dataKey="name"/><YAxis tickFormatter={v=>`${v/10000}万`}/><Tooltip formatter={v=>yen(Number(v))}/><Bar dataKey="revenue" name="売上" fill="#8b5cf6"/></BarChart></Plot><Table headings={['スタッフ','売上','来店数','客単価','再来客割合']} rows={staff.filter(s=>staffId==='all'||s.id===staffId).map(s=>[s.name,yen(s.revenue),`${s.count}件`,yen(s.average),`${s.repeat.toFixed(1)}%`])}/></TabsContent>
  <TabsContent value="store" className="space-y-5 mt-6"><Metrics entries={[['神戸店の売上',yen(summary.revenue)],['来店数',`${summary.visits}件`],['経費',yen(summary.cost)]]}/><Table headings={['店舗','売上','経費','利益（概算）','客単価']} rows={[["DEMO 神戸店",yen(summary.revenue),yen(summary.cost),yen(summary.profit),yen(summary.average)]]}/><p className="text-sm text-slate-500">このデモの登録店舗は神戸店のみです。下記は複数店舗運営時の比較例です。</p>{sample}<Plot title="複数店舗の比較イメージ"><BarChart data={[{name:'神戸店（例）',sales:2420000},{name:'大阪店（例）',sales:2160000},{name:'京都店（例）',sales:1850000}]}><XAxis dataKey="name"/><YAxis tickFormatter={v=>`${v/10000}万`}/><Tooltip/><Bar name="売上" dataKey="sales" fill="#10b981"/></BarChart></Plot></TabsContent>
  <TabsContent value="referral" className="space-y-5 mt-6">{sample}<Metrics entries={[['紹介による新規来店','18人'],['紹介客の再来率','72.2%'],['紹介経由の売上','¥151,200'],['紹介者数','12人']]}/><Table headings={['紹介元','新規客数','再来客数','売上']} rows={[["既存のお客様",12,9,'¥100,800'],['スタッフ紹介',4,3,'¥33,600'],['提携店舗',2,1,'¥16,800']]}/><Insight title="紹介されたお客様の定着" text="紹介後の初回来店時に、紹介者とのつながりやご希望を丁寧に確認する運用例です。" onAsk={()=>onAsk('再来率を改善するには？')}/></TabsContent>
  <TabsContent value="channel" className="space-y-5 mt-6"><p className="text-xs text-slate-500">デモ予約に架空の流入経路を均等に割り当てた集計です。</p><Plot title="流入経路別の来店数"><BarChart data={channels}><XAxis dataKey="name" tick={{fontSize:10}}/><YAxis/><Tooltip/><Bar dataKey="count" name="来店数" fill="#6366f1"/></BarChart></Plot><Table headings={['流入経路','来店数','売上','構成比']} rows={channels.map(c=>[c.name,c.count,yen(c.revenue),`${(c.count/Math.max(1,rows.length)*100).toFixed(1)}%`])}/></TabsContent>
  <TabsContent value="menu" className="space-y-5 mt-6"><label className="text-sm font-bold">メニュー<select className="block border p-2 rounded-lg mt-2 bg-white" value={menu} onChange={e=>setMenu(e.target.value)}><option value="all">すべてのメニュー</option>{menuNames.map(n=><option key={n}>{n}</option>)}</select></label><Plot title="メニュー別売上"><BarChart data={menus.filter(m=>menu==='all'||menu===m.name)}><XAxis dataKey="name" tick={{fontSize:10}}/><YAxis tickFormatter={v=>`${v/10000}万`}/><Tooltip formatter={v=>yen(Number(v))}/><Bar dataKey="revenue" name="売上" fill="#a78bfa"/></BarChart></Plot><Table headings={['メニュー','施術件数','売上','平均単価']} rows={menus.filter(m=>menu==='all'||menu===m.name).map(m=>[m.name,m.count,yen(m.revenue),yen(m.count?m.revenue/m.count:0)])}/></TabsContent>
  <TabsContent value="coupon" className="space-y-5 mt-6">{sample}<Metrics entries={[['比較クーポン','3件'],['予約率の改善例','+1.8pt'],['平均単価の改善例','+¥400']]}/><Table headings={['クーポン文言','価格','閲覧数','予約数','予約率']} rows={[["似合わせまつげパーマ",6500,800,48,'6.0%'],['初めての方へ・丁寧なカウンセリング付',6900,800,62,'7.8%'],['まつげ＋眉トータルデザイン',11000,500,30,'6.0%']]}/><Insight title="価格だけでなく、選ぶ理由を伝える" text="カウンセリングや仕上がりを具体的に伝える文言を、同じ期間・条件で比較するサンプルです。実際のクーポンは変更されません。" onAsk={()=>onAsk('改善策を教えて')}/></TabsContent>
  <TabsContent value="regression" className="space-y-5 mt-6">{sample}<Metrics entries={[['売上の前月比','−3.2%'],['新規客数の変化','0人'],['再来客数の変化','−10人'],['モデル決定係数（例）','0.82']]}/><Plot title="売上に対する要因の影響（説明用）"><BarChart data={[{name:'再来客数',impact:-78060},{name:'新規客数',impact:0},{name:'客単価など',impact:-1940}]}><XAxis dataKey="name"/><YAxis/><Tooltip formatter={v=>yen(Number(v))}/><Bar dataKey="impact" name="影響額" fill="#8b5cf6"/></BarChart></Plot><p className="text-sm text-slate-500">回帰モデルは実行していません。関連性の説明例であり、因果関係を断定するものではありません。</p></TabsContent>
  <TabsContent value="forecast" className="space-y-5 mt-6">{sample}<Plot title="売上予測と予測幅（固定シナリオ）"><LineChart data={forecast}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis tickFormatter={v=>`${v/10000}万`}/><Tooltip formatter={v=>yen(Number(v))}/><Legend/><Line dataKey="base" name="予測" stroke="#8b5cf6" strokeWidth={3}/><Line dataKey="low" name="下限例" stroke="#94a3b8" strokeDasharray="4 4"/><Line dataKey="high" name="上限例" stroke="#94a3b8" strokeDasharray="4 4"/></LineChart></Plot><Table headings={['月','予測売上','下限例','上限例']} rows={forecast.map(r=>[r.name,yen(r.base),yen(r.low),yen(r.high)])}/><p className="text-sm text-slate-500">本番のSARIMAX画面に対応する説明用サンプルです。学習・予測APIの呼出しは行いません。</p></TabsContent>
  <TabsContent value="repeat" className="space-y-5 mt-6"><Metrics entries={[['選択月の新規来店',`${summary.newVisits}件`],['選択月の再来来店',`${summary.repeatVisits}件`]]}/>{sample}<Table headings={['初回来店月','新規客数','30日以内再来率','60日以内再来率','90日以内再来率']} rows={[["2026年6月",100,'45%','59%','68%'],['2026年7月',100,'44%','58%','集計中'],['2026年8月',100,'42%','集計中','集計中'],['2026年9月',100,'34%','集計中','集計中']]}/><Insight title="30日以内再来率が8ポイント低下" text="来店後7日以内のLINEフォローや次回予約のご案内を見直す、営業説明用のシナリオです。" onAsk={()=>onAsk('再来率を改善するには？')}/></TabsContent>
  <TabsContent value="ltv" className="space-y-5 mt-6">{sample}<Metrics entries={[['年間LTV予測','¥46,800'],['年間来店回数予測','6.0回'],['継続客数予測','210人'],['継続客の年間売上予測','¥9,828,000']]}/><Plot title="来店後の累積利用額（説明用）"><AreaChart data={[{name:'初回',value:7800},{name:'3か月',value:15600},{name:'6か月',value:23400},{name:'9か月',value:39000},{name:'12か月',value:46800}]}><XAxis dataKey="name"/><YAxis/><Tooltip formatter={v=>yen(Number(v))}/><Area dataKey="value" name="累積利用額" stroke="#10b981" fill="#d1fae5"/></AreaChart></Plot></TabsContent>
  </Tabs>
 </section>;
}
function Plot({title,children}:{title:string;children:ReactElement}) {return <Card><CardHeader><CardTitle className="text-base">{title}</CardTitle></CardHeader><CardContent><div className="h-72 min-w-0"><ResponsiveContainer width="100%" height="100%" initialDimension={{width:600,height:288}}>{children}</ResponsiveContainer></div></CardContent></Card>;}
function Metrics({entries}:{entries:[string,string][]}) {return <div className="grid grid-cols-2 xl:grid-cols-4 gap-4">{entries.map(([name,value])=><Card key={name}><CardContent className="p-5"><p className="text-xs text-slate-500">{name}</p><p className="mt-3 text-xl font-black">{value}</p></CardContent></Card>)}</div>;}
function Table({headings,rows}:{headings:string[];rows:(string|number)[][]}) {return <div className="overflow-x-auto border rounded-xl bg-white"><table className="w-full text-sm whitespace-nowrap"><thead className="bg-slate-50"><tr>{headings.map(h=><th key={h} className="text-left p-4">{h}</th>)}</tr></thead><tbody>{rows.map((r,i)=><tr key={i} className="border-t">{r.map((c,j)=><td className="p-4" key={j}>{c}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className="p-5">対象データがありません。</p>}</div>;}
function Insight({title,text,onAsk}:{title:string;text:string;onAsk:()=>void}) {return <Card className="bg-purple-50 border-purple-100"><CardContent className="p-5 space-y-3"><h3 className="font-bold text-purple-900">{title}</h3><p className="text-sm text-slate-600">{text}</p><Button onClick={onAsk}><Sparkles size={16}/>改善策をAIに聞く</Button></CardContent></Card>;}
