'use client';
import SalonAgentLogo from "@/components/SalonAgentLogo";
import {useMemo,useState} from 'react';
import DemoEvaluations from './DemoEvaluations';
import DemoAnalytics from './DemoAnalytics';
import DemoPayroll from './DemoPayroll';
import {AreaChart,Area,XAxis,YAxis,CartesianGrid,Tooltip,ResponsiveContainer,BarChart,Bar,Cell} from 'recharts';
import {LayoutDashboard,CalendarDays,Users,Wallet,UserRound,ChartNoAxesCombined,Settings,Award,Sparkles,Menu,X,Upload,Plus,RotateCcw,Send,ChevronRight} from 'lucide-react';
import ExecutiveSummary from '@/components/dashboard/ExecutiveSummary';
import {Card,CardContent,CardHeader,CardTitle} from '@/components/ui/card';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Dialog,DialogContent,DialogHeader,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {createDemoData,demoSummary,demoAiReply,DEMO_STORE,DEMO_DATE,DEMO_MONTH,DEMO_TARGET,DEMO_MENUS,type DemoCustomer,type DemoReservation,type DemoStaff,type DemoExpense} from '@/lib/demo/data';
const money=(n:number)=>`¥${Math.round(n).toLocaleString('ja-JP')}`;
const tabs=[{id:'dashboard',name:'ダッシュボード',icon:LayoutDashboard},{id:'reservations',name:'予約カレンダー',icon:CalendarDays},{id:'customers',name:'顧客管理',icon:Users},{id:'sales',name:'売上管理',icon:Wallet},{id:'staff',name:'スタッフ分析',icon:UserRound},{id:'analysis',name:'高度分析',icon:ChartNoAxesCombined},{id:'evaluations',name:'評価制度・育成',icon:Award},{id:'payroll',name:'給与・報酬計算',icon:Wallet},{id:'expenses',name:'経費管理',icon:Wallet},{id:'settings',name:'設定・外部連携',icon:Settings}] as const;
type Tab=typeof tabs[number]['id'];
type FormKind='customer'|'reservation'|'expense'|'staff'|'csv'|'line'|'settings';
type Editor={kind:FormKind;id?:string};
export default function DemoApp() {
 const [dataset,setDataset]=useState(createDemoData),[tab,setTab]=useState<Tab>('dashboard'),[month,setMonth]=useState(DEMO_MONTH),[date,setDate]=useState(DEMO_DATE),[search,setSearch]=useState(''),[page,setPage]=useState(0);
 const [resetVersion,setResetVersion]=useState(0);
 const [mobile,setMobile]=useState(false),[editor,setEditor]=useState<Editor|null>(null),[notice,setNotice]=useState(''),[chatOpen,setChatOpen]=useState(false),[question,setQuestion]=useState('');
 const [messages,setMessages]=useState<{role:'user'|'ai';text:string}[]>([{role:'ai',text:'9月の売上は前月比3.2%減少しています。新規のお客様の再来状況に変化が見られます。原因を一緒に確認しましょう。'}]);
 const summary=useMemo(()=>demoSummary(dataset.reservations,dataset.expenses,month),[dataset,month]);
 const months=[...new Set(dataset.reservations.map(r=>r.date.slice(0,7)))].sort();
 const monthly=months.map(m=>({month:m.slice(5)+'月',...demoSummary(dataset.reservations,dataset.expenses,m)}));
 const current=dataset.reservations.filter(r=>r.date.startsWith(month)&&r.status!=='キャンセル');
 const staffStats=dataset.staff.map(s=>({...s,revenue:current.filter(r=>r.staffId===s.id).reduce((sum,r)=>sum+r.amount,0),count:current.filter(r=>r.staffId===s.id).length}));
 const calendarTimes=[...new Set(['09:00','11:00','13:00','15:00','17:00',...dataset.reservations.filter(r=>r.date===date&&r.status!=='キャンセル').map(r=>r.time)])].sort();
 const customers=dataset.customers.filter(c=>c.name.includes(search)||c.id.includes(search));
 function navigate(next:Tab){setTab(next);setPage(0);setSearch('');setMobile(false);setNotice('');}
 function ask(text=question){if(!text.trim())return;setMessages(m=>[...m,{role:'user',text:text.trim().slice(0,300)},{role:'ai',text:demoAiReply(text)}]);setQuestion('');setChatOpen(true);}
 function mock(message:string){setNotice(message+'（デモ）。実際のデータは変更されません。');}
 function save(values:Record<string,string>){
  if(!editor)return;const id=editor.id || `demo-added-${crypto.randomUUID()}`;
  setDataset(old=>{
   if(editor.kind==='customer'){const existing=old.customers.find(c=>c.id===id);const row:DemoCustomer={id,name:values.name,phone:'090-XXXX-0000',visits:existing?.visits||0,total:existing?.total||0,lastVisit:existing?.lastVisit||DEMO_DATE,line:existing?.line||false};return {...old,customers:existing?old.customers.map(c=>c.id===id?row:c):[row,...old.customers]};}
   if(editor.kind==='reservation'){const customer=old.customers.find(c=>c.id===values.customerId)!;const menu=DEMO_MENUS.find(m=>m.name===values.menu)!;const row:DemoReservation={id,date:values.date,time:values.time,customerId:customer.id,customerName:customer.name,staffId:values.staffId,menu:menu.name,amount:menu.price,isNew:false,status:'予約済み'};return {...old,reservations:editor.id?old.reservations.map(r=>r.id===id?row:r):[...old.reservations,row]};}
   if(editor.kind==='expense'){const row:DemoExpense={id,date:values.date,amount:Number(values.amount),category:values.category,memo:values.memo};return {...old,expenses:[row,...old.expenses]};}
   if(editor.kind==='staff'){const row:DemoStaff={id,name:values.name,role:'スタイリスト',color:'#8b5cf6'};return {...old,staff:[...old.staff,row]};}
   return old;
  });
  mock(editor.kind==='csv'?'CSVを取り込みました':editor.kind==='line'?'LINEフォローを送信しました':'保存しました');setEditor(null);
 }
 const activeTitle=tabs.find(t=>t.id===tab)!.name;
 return <div className="flex h-dvh overflow-hidden bg-slate-50 text-slate-900">
  {mobile&&<button className="fixed inset-0 z-30 bg-black/30 lg:hidden" aria-label="メニューを閉じる" onClick={()=>setMobile(false)}/>}
  <aside className={`${mobile?'translate-x-0':'-translate-x-full'} lg:translate-x-0 fixed lg:relative inset-y-0 left-0 z-40 w-64 shrink-0 bg-slate-900 text-white flex flex-col transition-transform`}>
   <div className="p-6"><SalonAgentLogo className="w-full h-auto" /></div>
   <div className="mx-4 mb-5 p-3 rounded-2xl bg-white/10 text-sm"><p className="text-[10px] text-slate-400 mb-1">勤務店舗</p><span className="text-emerald-400 mr-2">●</span>DEMO 神戸店</div>
   <nav aria-label="デモ内メニュー" className="flex-1 overflow-y-auto px-3 space-y-1">{tabs.map(t=><button key={t.id} className={`flex items-center gap-3 w-full text-left rounded-xl px-4 py-3 text-sm font-bold ${tab===t.id?'bg-blue-600 text-white':'text-slate-400 hover:bg-white/5 hover:text-white'}`} onClick={()=>navigate(t.id)}><t.icon size={20}/>{t.name}</button>)}</nav>
   <div className="m-4 rounded-2xl bg-white/5 p-4 text-sm"><p className="font-bold">デモ オーナー</p><p className="mt-1 text-xs text-slate-400">ログイン不要・架空のサロン</p><button className="mt-4 text-xs flex items-center gap-2 text-slate-300" onClick={()=>{setDataset(createDemoData());setResetVersion(v=>v+1);setMonth(DEMO_MONTH);setDate(DEMO_DATE);navigate('dashboard');setMessages([{role:'ai',text:'デモを初期状態に戻しました。9月の売上低下について確認してみましょう。'}]);mock('初期データに戻しました');}}><RotateCcw size={14}/>デモをリセット</button></div>
  </aside>
  <div className="flex flex-1 min-w-0 flex-col"><header className="h-16 shrink-0 border-b bg-white px-4 sm:px-7 flex items-center justify-between gap-3"><div className="flex items-center gap-3"><button className="lg:hidden" aria-label="メニューを開く" onClick={()=>setMobile(true)}><Menu/></button><span className="font-bold">{activeTitle}</span></div><div className="text-right"><span className="text-[10px] bg-amber-100 text-amber-800 font-bold rounded px-2 py-1">DEMO</span><p className="text-[10px] text-slate-500 mt-1">データはすべてサンプルです</p></div></header>
   <main className="flex-1 overflow-y-auto p-4 sm:p-7 pb-24"><div className="max-w-7xl mx-auto space-y-6">
    <div className="flex flex-wrap items-center justify-between gap-3"><div><h1 className="font-black text-2xl">{tab==='dashboard'?'サロンの今を、ひと目で。':activeTitle}</h1><p className="text-xs text-slate-500 mt-2">{DEMO_STORE} ／ デモ基準日：2026年9月30日</p></div><div className="flex gap-2">{['dashboard','sales','staff','analysis','expenses','payroll'].includes(tab)&&<select aria-label="集計月" value={month} onChange={e=>setMonth(e.target.value)} className="border bg-white rounded-lg p-2 text-sm">{months.map(m=><option key={m} value={m}>{m.replace('-','年')}月</option>)}</select>}<Button variant="outline" onClick={()=>setEditor({kind:'csv'})}><Upload size={15}/>CSV取込み</Button></div></div>
    {notice&&<div role="status" className="flex justify-between items-center bg-emerald-50 border border-emerald-200 p-3 rounded-xl text-sm">{notice}<button aria-label="通知を閉じる" onClick={()=>setNotice('')}><X size={16}/></button></div>}
    {tab==='dashboard'&&<>
     <ExecutiveSummary monthlyTotal={summary.revenue} regularVisits={summary.visits} minimoVisits={0} profit={summary.profit} projection={summary.revenue} storeStats={[{name:'DEMO 神戸店',current:summary.revenue,target:DEMO_TARGET}]}/>
     <section className="rounded-2xl border border-indigo-100 bg-gradient-to-r from-indigo-50 to-white p-5"><div className="flex items-start gap-3"><div className="bg-indigo-600 text-white rounded-xl p-2"><Sparkles/></div><div className="flex-1"><p className="text-xs font-bold text-indigo-600">先回りAI秘書・サンプル分析</p><h2 className="text-lg font-bold mt-1">9月の売上が前月比3.2%減少しています</h2><p className="text-sm text-slate-600 mt-2">新規客の30日以内再来率が8ポイント低下。来店後のフォローを見直すタイミングです。</p><div className="flex flex-wrap gap-2 mt-4"><Button onClick={()=>ask('今月売上が下がっている理由は？')}>AIに「なぜ？」と聞く<ChevronRight size={15}/></Button><Button variant="outline" onClick={()=>navigate('analysis')}>顧客分析を見る</Button><Button variant="outline" onClick={()=>setEditor({kind:'line'})}>LINEフォローを体験</Button></div></div></div></section>
     <div className="grid xl:grid-cols-2 gap-5"><Chart title="12か月の売上推移"><AreaChart data={monthly}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="month"/><YAxis tickFormatter={v=>`${Number(v)/10000}万`} width={50}/><Tooltip formatter={v=>money(Number(v))}/><Area type="monotone" dataKey="revenue" name="売上" stroke="#6366f1" fill="#e0e7ff"/></AreaChart></Chart><Chart title="スタッフ別売上"><BarChart data={staffStats}><CartesianGrid strokeDasharray="3 3"/><XAxis dataKey="name"/><YAxis tickFormatter={v=>`${Number(v)/10000}万`} width={50}/><Tooltip formatter={v=>money(Number(v))}/><Bar dataKey="revenue" name="売上" radius={[6,6,0,0]}>{staffStats.map(s=><Cell key={s.id} fill={s.color}/>)}</Bar></BarChart></Chart></div>
    </>}
    {tab==='reservations'&&<>
     <div className="flex flex-wrap gap-3 items-center"><input aria-label="予約日" type="date" className="border rounded p-2 bg-white" value={date} onChange={e=>setDate(e.target.value)}/><Button onClick={()=>setEditor({kind:'reservation'})}><Plus size={15}/>予約追加</Button><span className="text-sm text-slate-500">{dataset.reservations.filter(r=>r.date===date&&r.status!=='キャンセル').length}件の予約</span></div>
     <div className="overflow-x-auto rounded-2xl border bg-white"><table className="min-w-[720px] w-full text-sm"><thead><tr className="bg-slate-100"><th className="p-4 text-left">スタッフ／時間</th>{calendarTimes.map(t=><th key={t} className="p-4">{t}</th>)}</tr></thead><tbody>{dataset.staff.map(s=><tr key={s.id}><th className="p-4 border-t text-left w-36">{s.name}</th>{calendarTimes.map(t=><td key={t} className="border-t border-l align-top p-2 h-32 min-w-36">{dataset.reservations.filter(r=>r.date===date&&r.staffId===s.id&&r.time===t&&r.status!=='キャンセル').map(r=><button key={r.id} className="block w-full rounded-lg bg-indigo-50 border-l-4 border-indigo-400 p-3 text-left mb-2 hover:bg-indigo-100" onClick={()=>setEditor({kind:'reservation',id:r.id})}><span className="font-bold block">{r.customerName}</span><span className="text-xs block mt-1">{r.menu}</span><span className="text-[10px] text-indigo-600">{r.status}</span></button>)}</td>)}</tr>)}</tbody></table></div><p className="text-sm text-slate-500">予約を押すと、日時変更やキャンセルの操作を体験できます。</p>
    </>}
    {tab==='customers'&&<>
     <div className="flex gap-3"><Input placeholder="顧客名を検索" aria-label="顧客名を検索" value={search} onChange={e=>{setSearch(e.target.value);setPage(0);}}/><Button onClick={()=>setEditor({kind:'customer'})}><Plus size={16}/>顧客登録</Button></div><p className="text-sm text-slate-500">{customers.length}名のサンプル顧客 ／ 電話番号はダミー表示</p>
     <DataTable headings={['お客様','来店回数','累計売上','最終来店','LINE','操作']} rows={customers.slice(page*12,page*12+12).map(c=>[c.name,`${c.visits}回`,money(c.total),c.lastVisit,c.line?'連携済み':'未連携',<Button key={c.id} size="sm" variant="outline" onClick={()=>setEditor({kind:'customer',id:c.id})}>詳細・編集</Button>])}/><div className="flex gap-3"><Button variant="outline" disabled={page===0} onClick={()=>setPage(p=>p-1)}>前へ</Button><span className="p-2">{page+1} / {Math.max(1,Math.ceil(customers.length/12))}</span><Button variant="outline" disabled={(page+1)*12>=customers.length} onClick={()=>setPage(p=>p+1)}>次へ</Button></div>
    </>}
    {tab==='sales'&&<><MetricCards entries={[['売上',money(summary.revenue)],['来店数',`${summary.visits}件`],['客単価',money(summary.average)],['目標達成率',`${(summary.revenue/DEMO_TARGET*100).toFixed(1)}%`]]}/><DataTable headings={['日付','顧客','メニュー','担当','売上']} rows={current.slice(-30).reverse().map(r=>[r.date,r.customerName,r.menu,dataset.staff.find(s=>s.id===r.staffId)?.name||'',money(r.amount)])}/><p className="text-xs text-slate-500">選択月の直近30件を表示。月間集計は全件を対象としています。</p></>}
    {tab==='staff'&&<><div className="flex justify-end"><Button onClick={()=>setEditor({kind:'staff'})}><Plus size={15}/>スタッフ登録</Button></div><div className="grid md:grid-cols-3 gap-4">{staffStats.map(s=><Card key={s.id}><CardHeader><CardTitle>{s.name}</CardTitle><p className="text-sm text-slate-500">{s.role}</p></CardHeader><CardContent className="space-y-3"><p className="text-3xl font-black">{money(s.revenue)}</p><p>担当件数：{s.count}件</p><p>客単価：{money(s.count?s.revenue/s.count:0)}</p><div className="h-2 bg-slate-100 rounded-full"><div className="h-2 rounded-full" style={{width:`${Math.min(100,s.revenue/900000*100)}%`,background:s.color}}/></div><p className="text-xs text-slate-500">個人目標 ¥900,000</p></CardContent></Card>)}</div></>}
    {tab==='analysis'&&<DemoAnalytics dataset={dataset} month={month} onAsk={ask}/>}
    <div hidden={tab!=='evaluations'}><DemoEvaluations key={resetVersion} staff={dataset.staff}/></div>
    <div hidden={tab!=='payroll'}><DemoPayroll key={resetVersion} staff={dataset.staff} month={month}/></div>
    {tab==='expenses'&&<><MetricCards entries={[['月間経費',money(summary.cost)],['売上−経費',money(summary.profit)],['経費率',`${(summary.cost/Math.max(1,summary.revenue)*100).toFixed(1)}%`]]}/><Button onClick={()=>setEditor({kind:'expense'})}><Plus size={15}/>経費を追加</Button><DataTable headings={['日付','カテゴリ','摘要','金額']} rows={dataset.expenses.filter(e=>e.date.startsWith(month)).map(e=>[e.date,e.category,e.memo,money(e.amount)])}/></>}
    {tab==='settings'&&<div className="grid md:grid-cols-2 gap-5">{['店舗・業種設定','LINE連携','会計ソフト連携','スタッフ名の紐づけ'].map(label=><Card key={label}><CardHeader><CardTitle>{label}</CardTitle></CardHeader><CardContent><p className="text-sm text-slate-500 mb-4">設定・連携の操作イメージを確認できます。</p><Button variant="outline" onClick={()=>setEditor({kind:label==='LINE連携'?'line':'settings'})}>設定を開く</Button></CardContent></Card>)}</div>}
   </div></main>
  </div>
  <button aria-label="AI秘書を開く" onClick={()=>setChatOpen(true)} className="fixed right-5 bottom-5 rounded-full bg-indigo-600 text-white p-4 shadow-xl z-20"><Sparkles size={25}/></button>
  {chatOpen&&<section aria-label="先回りAI秘書" className="fixed bottom-4 right-3 sm:right-5 w-[calc(100%-24px)] sm:w-[420px] max-h-[80dvh] flex flex-col rounded-2xl bg-white border shadow-2xl z-50"><header className="bg-indigo-600 text-white p-4 rounded-t-2xl flex justify-between items-center"><span className="font-bold flex items-center gap-2"><Sparkles size={19}/>先回りAI秘書</span><button aria-label="AI秘書を閉じる" onClick={()=>setChatOpen(false)}><X size={20}/></button></header><p className="text-[10px] text-slate-500 px-4 pt-2">サンプル回答・初期データの分析シナリオ</p><div className="overflow-y-auto p-4 space-y-3" aria-live="polite">{messages.map((m,i)=><p key={i} className={`text-sm leading-7 rounded-xl p-3 whitespace-pre-wrap ${m.role==='ai'?'bg-slate-50':'bg-indigo-50 ml-8'}`}>{m.text}</p>)}</div><div className="px-3 flex gap-2 flex-wrap"><button className="text-xs text-indigo-700 border rounded-full px-3 py-1" onClick={()=>ask('今月売上が下がっている理由は？')}>なぜ売上が低下？</button><button className="text-xs text-indigo-700 border rounded-full px-3 py-1" onClick={()=>ask('改善策を教えて')}>改善策を教えて</button></div><form className="p-3 flex gap-2" onSubmit={e=>{e.preventDefault();ask();}}><Input aria-label="AIへの質問" maxLength={300} placeholder="気になることを質問…" value={question} onChange={e=>setQuestion(e.target.value)}/><Button type="submit" aria-label="質問を送信"><Send size={17}/></Button></form></section>}
  <Dialog open={!!editor} onOpenChange={open=>{if(!open)setEditor(null);}}><DialogContent className="max-h-[90dvh] overflow-y-auto"><DialogHeader><DialogTitle>{editor?.kind==='csv'?'CSV取込み':editor?.kind==='line'?'LINEフォロー':editor?.kind==='customer'?'顧客情報':editor?.kind==='reservation'?'予約情報':editor?.kind==='expense'?'経費登録':editor?.kind==='staff'?'スタッフ登録':'設定'}</DialogTitle><DialogDescription>デモ環境のため、実際のデータは変更されません。</DialogDescription></DialogHeader>{editor&&<DemoEditor key={`${editor.kind}:${editor.id||'new'}`} editor={editor} dataset={dataset} date={date} onSave={save} onCancelReservation={()=>{setDataset(old=>({...old,reservations:old.reservations.map(r=>r.id===editor.id?{...r,status:'キャンセル'}:r)}));mock('予約をキャンセルしました');setEditor(null);}}/>}</DialogContent></Dialog>
 </div>;
}
function Chart({title,children}:{title:string;children:React.ReactElement}){return <Card><CardHeader><CardTitle className="text-base">{title}</CardTitle></CardHeader><CardContent><div className="h-64 min-w-0"><ResponsiveContainer width="100%" height="100%" initialDimension={{width:600,height:256}}>{children}</ResponsiveContainer></div></CardContent></Card>;}
function MetricCards({entries}:{entries:[string,string][]}){return <div className="grid grid-cols-2 xl:grid-cols-4 gap-4">{entries.map(([label,value])=><Card key={label}><CardContent className="p-5"><p className="text-xs text-slate-500 font-bold">{label}</p><p className="mt-3 text-2xl font-black">{value}</p></CardContent></Card>)}</div>;}
function DataTable({headings,rows}:{headings:string[];rows:React.ReactNode[][]}){return <div className="overflow-x-auto border rounded-2xl bg-white"><table className="w-full text-sm whitespace-nowrap"><thead><tr className="bg-slate-50">{headings.map(h=><th key={h} className="p-4 text-left text-slate-500 font-bold">{h}</th>)}</tr></thead><tbody>{rows.map((row,i)=><tr key={i} className="border-t hover:bg-slate-50">{row.map((cell,j)=><td key={j} className="p-4">{cell}</td>)}</tr>)}</tbody></table>{!rows.length&&<p className="p-8 text-slate-500">対象のサンプルデータがありません。</p>}</div>;}
function DemoEditor({editor,dataset,date,onSave,onCancelReservation}:{editor:Editor;dataset:ReturnType<typeof createDemoData>;date:string;onSave:(values:Record<string,string>)=>void;onCancelReservation:()=>void}){
 const reservation=dataset.reservations.find(r=>r.id===editor.id),customer=dataset.customers.find(c=>c.id===editor.id);
 const [values,setValues]=useState<Record<string,string>>({name:customer?.name||'',date:reservation?.date||date,time:reservation?.time||'09:00',customerId:reservation?.customerId||dataset.customers[0].id,staffId:reservation?.staffId||dataset.staff[0].id,menu:reservation?.menu||DEMO_MENUS[0].name,amount:'5000',category:'材料費',memo:'サンプル経費'});
 const field=(key:string,label:string,type='text')=><label className="block text-sm font-bold">{label}<Input name={key} className="mt-2" required maxLength={100} min={type==='number'?0:undefined} type={type} value={values[key]} onChange={e=>setValues(v=>({...v,[key]:e.target.value}))}/></label>;
 return <form className="space-y-4" onSubmit={e=>{e.preventDefault();onSave({...values,...Object.fromEntries(new FormData(e.currentTarget).entries())} as Record<string,string>);}}>
  {['customer','staff'].includes(editor.kind)&&<>{field('name','お名前')}<p className="text-xs text-slate-500">入力はこの画面内だけで保持し、送信・保存しません。</p></>}
  {editor.kind==='customer'&&<p className="text-sm">電話番号：{customer?.phone||'090-XXXX-0000'} ／ LINE：{customer?.line?'連携済み':'未連携'}<br/>来店履歴：{customer?.visits||0}回</p>}
  {editor.kind==='reservation'&&<>{field('date','予約日','date')}{field('time','開始時間','time')}{[['customerId','お客様',dataset.customers.filter((c,i)=>i<100||c.id===values.customerId).map(c=>[c.id,c.name])],['staffId','担当スタッフ',dataset.staff.map(s=>[s.id,s.name])],['menu','メニュー',DEMO_MENUS.map(m=>[m.name,m.name])]].map(([key,label,options])=><label key={key as string} className="block text-sm font-bold">{label as string}<select name={key as string} className="block w-full border rounded-lg p-2 mt-2" value={values[key as string]} onChange={e=>setValues(v=>({...v,[key as string]:e.target.value}))}>{(options as string[][]).map(([value,text])=><option key={value} value={value}>{text}</option>)}</select></label>)}</>}
  {editor.kind==='expense'&&<>{field('date','日付','date')}{field('category','カテゴリ')}{field('amount','金額','number')}{field('memo','摘要')}</>}
  {editor.kind==='csv'&&<div className="rounded-xl border-2 border-dashed p-6 bg-slate-50 text-center"><Upload className="mx-auto mb-3 text-indigo-500"/><p className="font-bold">demo-sales-2026-09.csv</p><p className="text-sm text-slate-500 mt-2">HOT PEPPER Beauty形式のサンプルを取込みます。実ファイルの選択・読み取り・アップロードは行いません。</p></div>}
  {editor.kind==='line'&&<div className="p-4 rounded-xl bg-emerald-50 text-sm leading-7"><p className="font-bold">来店後フォローのサンプル</p><p>先日はご来店ありがとうございました。その後の状態はいかがでしょうか？お手入れなど気になることがあれば、お気軽にお声がけください。</p><p className="mt-3 text-xs">架空のお客様への送信操作のみ体験できます。</p></div>}
  {editor.kind==='settings'&&<><label className="block text-sm">業種<select className="block border rounded p-2 mt-2 w-full"><option>まつ毛・眉</option><option>美容室</option><option>ネイル</option></select></label><p className="text-sm text-slate-500">外部サービスへの認証・接続は行いません。</p></>}
  <div className="flex flex-wrap gap-3"><Button type="submit">{editor.kind==='csv'?'CSV取込みを体験':editor.kind==='line'?'送信を体験':'保存する（デモ）'}</Button>{editor.kind==='reservation'&&editor.id&&<Button type="button" variant="destructive" onClick={onCancelReservation}>予約をキャンセル（デモ）</Button>}</div>
 </form>;
}
